### ISSUE TITLE
TypeError: 'Flask' object is not iterable

### ISSUE THREAD

**Issue by abuvanth** [openprocurement/openprocurement.api#224]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 182, in handle_request
    for item in respiter:
TypeError: 'Flask' object is not iterable

**Comment by ManuelCAT1** [comment]
did you solve this?
